id: D00B0B441
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-08T06:42:51+00:00'
last_modified: '2022-05-26T14:25:12.265255+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e741:
      image_group_id: I1PD95885
      title: འཕགས་མ་སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      order: 40
      base_file: e741.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
