id: P0B292FCB
initial_creation_type: ocr
source_metadata:
  volumes:
    7728aafe2bac49b08d92d661a5efcdd1:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་མ་སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
